### ISSUE TITLE
Http Parser

### ISSUE THREAD

**Issue by Alex-dev02** [Alex-dev02/SimpleWebServer#5]
Write a small Http Parser that would be able to extract the HTTP verb, path, query params and body.
Follow [this](https://www.jmarshall.com/easy/http/) guide.

The parser should:
- be instantiated with the raw HTTP string request: `HttpParser parser(myRawHttpRequest)`
- have members for saving the : Request type (Get/post/put/delete), path (/my/res/123), http version, query params (/my/res/path?value=123&value2=abs) in an unordered_map
- have member functions to extract all the data ^^^

**Comment by stevenstonie** [comment]
whoops

**Comment by stevenstonie** [comment]
Hi there. I have done some work and made some commits these days, however, i ran into a minor problem, which is being unable to push to remote due to an authentication error for git. It seems that as of 13th of August, 2021 the "Support for password authentication was removed". I have succesfully added the ssh key to my github account but i am unable to finish with the authentication problem at the moment. I will, however, continue on working on it some time tomorrow (technically today). Best Regards!
